  services:
    todo-list:
      image: mohamedsamir170/todolist:latest
      container_name: todo-list
      ports:
        - "4010:4000"
      volumes:
        - ./:/app
        - /app/node_modules
      networks:
        - app-network
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4000/"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 5s
  
    watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --interval 30 todo-list
      environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_POLL_INTERVAL=30
        - WATCHTOWER_DEBUG=true
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge
