---
- name: Deploy application using Docker Compose
  hosts: webservers
  become: true
  vars:
    app_name: "myapp"
    app_directory: "/home/ubuntu/{{ app_name }}"
    source_dir: "{{ playbook_dir }}/.."

  tasks:
    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Copy application files excluding node_modules and .git
      synchronize:
        src: "{{ source_dir }}/"
        dest: "{{ app_directory }}/"
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=.git"
        recursive: yes
    - name: Deploy the application with Docker Compose
      command: docker compose up -d --build
      args:
        chdir: "{{ app_directory }}"