apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-list
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohamedsamir170/todolist.git'
    path: overlays
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy: 
    automated:
      selfHeal: true
      prune: true
