apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-list-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: todo-list-pvc
      containers:
        - name: todo-list
          image: mohamedsamir170/todolist:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:  
            - name: app-storage
              mountPath: /app/data
